version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - mongo
    command: npm start
  mongo:
    image: mongo
    volumes:
      - /Users/bbq923/mongodb-data:/data/db
    ports:
      - "27017:27017"